

services:
  server:
    build:
      context: .                # Use the root directory as context
      dockerfile: Dockerfile    # Reference the Dockerfile at the root
    ports:
      - "3001:3001"
    env_file:                   # Load environment variables from the .env file
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

  client:
    build:
      context: ./client         # Set the build context to the client directory
      dockerfile: Dockerfile    # Use the Dockerfile within the client directory
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
